## Practice Questions for numpy
1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.
2. Find common elements between A and B. [Hint : Intersection of two sets]
3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]
4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0 
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [5]:
# 1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])
vestack = np.vstack((A, B))
hostack = np.hstack((A, B))
vestack, hostack

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]),
 array([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]]))

In [7]:
# 2. Find common elements between A and B. [Hint : Intersection of two sets]
comelements = np.intersect1d(A, B)
comelements

array([], dtype=int32)

In [18]:
# 3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]inrange = np.where((A >= 5) & (A <= 10))
inrange = np.where((A >= 5) & (A <= 10))
numbers_in_range = A[inrange]
numbers_in_range

array([5, 6])

In [32]:
#4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0 
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

filtered_iris2d = iris_2d[(iris_2d[:,2]>1.5) & (iris_2d[:,0] < 5)]
filtered_iris2d

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

## Practice Questions for Pandas

1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

3. How to get the rows of a dataframe with row sum > 100?

```
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [45]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                 NaN      Front  ...        7.0   187.0   
89         30.0                 NaN      Front  ...        5.0   180.0   
90         25.0                 NaN      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [43]:
# 1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
filtered_df

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [46]:
# 2. Replace missing values in Min.Price and Max.Price columns with their respective mean.
mean_min_price = df['Min.Price'].mean()
mean_max_price = df['Max.Price'].mean()

df['Min.Price'] = df['Min.Price'].fillna(mean_min_price)
df['Max.Price'] = df['Max.Price'].fillna(mean_max_price)
df

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                 NaN      Front  ...        7.0   187.0   
89         30.0                 NaN      Front  ...        5.0   180.0   
90         25.0                 NaN      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [4]:
# 3. How to get the rows of a dataframe with row sum > 100?
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df

0   1   2   3
0   35  35  11  12
1   10  22  13  23
2   33  30  20  15
3   18  29  26  20
4   31  24  34  15
5   27  23  11  10
6   37  23  29  24
7   23  15  17  24
8   10  23  16  19
9   35  23  21  35
10  32  36  35  19
11  15  17  36  11
12  37  30  17  21
13  24  10  32  10
14  10  10  12  39

In [7]:
rows_with_sum_100 = df[df.sum(axis) > 100]
rows_with_sum_100

C:\Users\82044\AppData\Local\Temp\ipykernel_16964\2355582540.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  rows_with_sum_100 = df[df.sum(axis=0) > 100]


IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).